"use client";

import { useEffect, useRef, useState } from "react";
import { Card } from "@/components/ui/card";
import ChatMessage from "./ChatMessages";
import ChatInput from "./ChatInput";
import type { ChatMessage as Message } from "../types";

const dummyMessages: Message[] = [
    { id: "1", role: "assistant", content: "Hi! How can I help you today?" },
    { id: "2", role: "user", content: "Show me warehouse stock summary." },
];

export default function ChatWindow({ chatId }: { chatId: string }) {
    const [messages, setMessages] = useState<Message[]>(dummyMessages);
    const bottomRef = useRef<HTMLDivElement>(null);

    useEffect(() => {
        bottomRef.current?.scrollIntoView({ behavior: "smooth" });
    }, [messages]);

    const handleSend = (text: string) => {
        setMessages(prev => [
            ...prev,
            { id: crypto.randomUUID(), role: "user", content: text },
            {
                id: crypto.randomUUID(),
                role: "assistant",
                content: "This will be generated by the backend.",
            },
        ]);
    };

    return (
        <div
            className="flex flex-col flex-1 min-h-0">
            {/* Messages */}
            <div className="flex-1 overflow-y-auto px-6 py-10 space-y-10 chat-scroll">
                <div className="mx-auto px-6 py-6 space-y-6 max-w-5xl">
                    {messages.map(msg => (
                        <ChatMessage key={msg.id} message={msg} />
                    ))}
                    <div ref={bottomRef} />
                </div>
            </div>

            {/* Input */}
            <div className=" bg-background/80 backdrop-blur">
                <ChatInput onSend={handleSend} />
            </div>
        </div>
    );
}
